version: "3.8"
services:
  postgres:
    container_name: ks-postgres
    image: postgres:10.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    networks:
      - global
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db:/var/lib/postgresql/data
  redis:
    container_name: ks-redis
    image: redis:alpine
    restart: always
    networks:
      - default
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

networks:
  global:
    name: global
volumes:
  redis:
    driver: local
  db:
    driver: local
